### ISSUE TITLE
You can improve your repository documentation with Snorkell.ai

### ISSUE THREAD

**Issue by sumansaurabh** [theleharo/evkafka#2]
I know it might feel like I am spamming. 

You can actually give a try to Snorkell.ai, Github App, an automatic "contextual" documentation generation tool for Typescript Classes and Methods.

Once installed, Snorkell automatically generates comprehensive documentation for all Typescript Classes and Functions in your project. This seamless integration operates in the background, eliminating the need for manual intervention.

Additionally, Snorkell.ai is not a static tool; it continuously and dynamically updates the documentation to reflect any changes made to your functions.

For every update sent to your Github Repo, Snorkell.ai creates a PR containing the updated documentation. This allows you to review and merge the changes, ensuring that you maintain oversight and control over your project's documentation.

Reference links: 
1. https://github.com/apps/snorkell-ai
2. Demo: https://youtu.be/rXMW1xAA-RU

**Comment by theleharo** [comment]
yes you are
